### PR TITLE
core: make gpiod_strerror() work with musl

### PR DESCRIPTION
**Pull request by brgl**
Hi @tpetazzoni,

this patch addresses the strerror_r() issue with musl. Could you please take a look and let me know what you think? Do you know a better approach by any chance?

### CODE REVIEW

**Comment by pcercuei** [comment]
What you could do, is #undef _GNU_SOURCE just in that file, to make sure you always get the XSI version.

**Comment by brgl** [comment]
> What you could do, is #undef _GNU_SOURCE just in that file, to make sure you always get the XSI version.

This file contains all the library code. I could potentially just move the strerror_wrapper() routine into a different file, but I specifically _want_ GNU extensions in my code, so I prefer not to undef it just to make a libc happy.

BTW any reason why musl doesn't provide the POSIX version? Would Rich Felker reject a patch adding it?

**Comment by tpetazzoni** [comment]
Well, musl precisely provides the POSIX version, it's the one that returns an int. The one returning a char* is GNU specific. Look at the strerror_r() manpage, it says:

```
       The strerror_r() function is similar to strerror(), but is thread safe.
       This  function  is  available in two versions: an XSI-compliant version
       specified in POSIX.1-2001 (available since glibc 2.3.4, but not  POSIX-
       compliant  until  glibc  2.13),  and  a GNU-specific version (available
       since glibc 2.0).
```

And also:

```
       The  XSI-compliant strerror_r() is preferred for portable applications.
```

**Comment by brgl** [comment]
Eeek! -ECONFUSED

I misread the manual - now I get it. My solution is wrong anyway as since glibc 2.13 the POSIX version returns a positive error number on failure. I'll move the wrapper to a separate file and undef _GNU_SOURCE then.

**Pull request closed without merging**
