### PR TITLE
shared-ptr deleter is called even if ptr is nullptr (fix #35)

### LINKED ISSUE #35: If there is no /dev/gpiochip-device, cxx-binding is crashing
I'm simply running gpiodetectcxx.cpp on my PC, where there is no gpiochip in /dev. It quits with a segfault.

The problem is, that the chip_iter is creating a `chip` with a `gpiod_chip` set to `NULL` and the deleter is calling `::gpiod_chip_close(chip);` which crashes because it dereferences a NULL-pointer.

I don't know how to fix it properly. I added locally a NULL-check inside the gpiod_chip_close-function.

### PR DESCRIPTION
**Pull request by pboettch**
Could not resist, I'm so impatient :-/.

### CODE REVIEW

**Comment by brgl** [comment]
You're fixing the iter objects - but AFAICT the problem is with the chip object. Was that on purpose?

**Comment by pboettch** [comment]
Of course not. Sorry.

But seeing again where there are deleters in the binding makes me wonder whether it was correct to create a shared_ptr owning a nullptr in the first place.

**Comment by brgl** [comment]
Yes, this is my other concern - we should probably check if the C function returned a null pointer and then not initialize the chip object.

**Comment by pboettch** [comment]
Yes, as you do in `chip_iter& chip_iter::operator++(void)`

**Comment by pboettch** [comment]
It's maybe better like this now.

**Comment by brgl** [comment]
Yes, it looks good now. Can you send it to linux-gpio with [PATCH][libgpiod] tag and your Signed-off-by: tag? I use patchwork for patch management. This github repo is not really the official development tool for me.

**Comment by pboettch** [comment]
Too bad. GIthub/lab review/pr/merge is so superior to mailing lists-review - IMHO.

But I will try to do it, git-send-email-galore. git-format-patch. Oh lala ;-).

**Comment by pboettch** [comment]
Of course I messed up the mail. I didn't know how to add the [libgpiod]-tag to the subject-line. So I added it to the commit-message. Re-run format-patch and send send-email the wrong-file.

**Pull request closed without merging**
